index:
   path: /
   # controller: App\Controller\SecurityController::login
   controller: App\Controller\HomeController::index

google_login:
    path: /connect/google
    controller: App\Controller\SecurityController::connectGoogle

connect_google_check:
    path: /connect/google/check
